/*
 * sensor_fusion.ino — Arduino UNO Q (Qualcomm Cortex-M55 + Ethos-U55 NPU)
 *
 * Reads 5 sensors, runs TFLite classifier on NPU, outputs state label at 1Hz.
 *
 * Output JSON to Pi (USB Serial):
 *   {"state":"FOCUSED","confidence":0.91,"sensors":{"dist":42,"vib":1,"light":310,"cap":0}}
 *
 * States: FOCUSED | IDLE | DOZING | AWAY
 *
 * Wiring:
 *   Grove Ultrasonic  → D7
 *   Piezo vibration   → A0
 *   Photocell         → A1
 *   Capacitive touch  → A2
 *   Grove IMU (I2C)   → SDA/SCL
 */

#include <Arduino.h>
#include <Wire.h>
#include <ArduinoJson.h>

// TFLite — Arduino_TensorFlowLite library
#include <TensorFlowLite.h>
#include <tensorflow/lite/micro/all_ops_resolver.h>
#include <tensorflow/lite/micro/micro_interpreter.h>
#include <tensorflow/lite/schema/schema_generated.h>

// Trained model (generated by train_model.py, converted to C array)
#include "focus_model_data.h"

// ── Pin definitions ────────────────────────────────────────────────────────
#define PIN_ULTRASONIC  7
#define PIN_VIBRATION   A0
#define PIN_PHOTOCELL   A1
#define PIN_CAPACITIVE  A2

// ── TFLite setup ───────────────────────────────────────────────────────────
constexpr int TENSOR_ARENA_SIZE = 32 * 1024;  // 32KB — tune to model size
static uint8_t tensor_arena[TENSOR_ARENA_SIZE];

const tflite::Model*          model_ptr = nullptr;
tflite::MicroInterpreter*     interpreter = nullptr;
TfLiteTensor*                 input  = nullptr;
TfLiteTensor*                 output = nullptr;

// Class labels matching training order
const char* LABELS[] = {"FOCUSED", "IDLE", "DOZING", "AWAY"};
const int   NUM_CLASSES = 4;

// ── Ultrasonic helper ──────────────────────────────────────────────────────
long readDistanceCm() {
  pinMode(PIN_ULTRASONIC, OUTPUT);
  digitalWrite(PIN_ULTRASONIC, LOW);
  delayMicroseconds(2);
  digitalWrite(PIN_ULTRASONIC, HIGH);
  delayMicroseconds(10);
  digitalWrite(PIN_ULTRASONIC, LOW);
  pinMode(PIN_ULTRASONIC, INPUT);
  long duration = pulseIn(PIN_ULTRASONIC, HIGH, 30000);  // 30ms timeout
  return duration / 58;  // cm
}

// ── Vibration debounce ─────────────────────────────────────────────────────
int vibrationCount = 0;
unsigned long lastVibCheck = 0;
#define VIB_WINDOW_MS 1000

bool checkVibration() {
  int raw = analogRead(PIN_VIBRATION);
  if (raw > 512) vibrationCount++;
  unsigned long now = millis();
  if (now - lastVibCheck >= VIB_WINDOW_MS) {
    bool active = vibrationCount > 3;
    vibrationCount = 0;
    lastVibCheck = now;
    return active;
  }
  return false;
}

// ── Setup ──────────────────────────────────────────────────────────────────
void setup() {
  Serial.begin(115200);
  Wire.begin();
  pinMode(PIN_CAPACITIVE, INPUT);

  // Load TFLite model
  model_ptr = tflite::GetModel(focus_model_data);
  if (model_ptr->version() != TFLITE_SCHEMA_VERSION) {
    Serial.println("{\"error\":\"TFLite schema mismatch\"}");
    while (1);
  }

  static tflite::AllOpsResolver resolver;
  static tflite::MicroInterpreter static_interpreter(
    model_ptr, resolver, tensor_arena, TENSOR_ARENA_SIZE
  );
  interpreter = &static_interpreter;
  interpreter->AllocateTensors();

  input  = interpreter->input(0);
  output = interpreter->output(0);

  Serial.println("{\"status\":\"sensor_fusion_ready\"}");
}

// ── Main loop ──────────────────────────────────────────────────────────────
unsigned long lastOutputMs = 0;
#define OUTPUT_INTERVAL_MS 1000

void loop() {
  // Read sensors
  long distCm   = readDistanceCm();
  bool vibActive = checkVibration();
  int  light     = analogRead(PIN_PHOTOCELL);
  int  cap       = digitalRead(PIN_CAPACITIVE);

  // Build feature vector — must match training feature order:
  // [dist_norm, vib, light_norm, cap, person_present]
  float distNorm  = constrain((float)distCm / 200.0f, 0.0f, 1.0f);
  float lightNorm = constrain((float)light  / 1023.0f, 0.0f, 1.0f);
  float personPresent = (distCm > 0 && distCm < 80) ? 1.0f : 0.0f;

  input->data.f[0] = distNorm;
  input->data.f[1] = vibActive ? 1.0f : 0.0f;
  input->data.f[2] = lightNorm;
  input->data.f[3] = (float)cap;
  input->data.f[4] = personPresent;

  // Run inference on NPU
  TfLiteStatus status = interpreter->Invoke();
  if (status != kTfLiteOk) {
    Serial.println("{\"error\":\"inference_failed\"}");
    return;
  }

  // Find highest-confidence class
  int   bestClass = 0;
  float bestConf  = output->data.f[0];
  for (int i = 1; i < NUM_CLASSES; i++) {
    if (output->data.f[i] > bestConf) {
      bestConf  = output->data.f[i];
      bestClass = i;
    }
  }

  // Output at 1Hz
  unsigned long now = millis();
  if (now - lastOutputMs >= OUTPUT_INTERVAL_MS) {
    lastOutputMs = now;

    StaticJsonDocument<256> doc;
    doc["state"]      = LABELS[bestClass];
    doc["confidence"] = round(bestConf * 100) / 100.0;

    JsonObject sensors = doc.createNestedObject("sensors");
    sensors["dist"]  = distCm;
    sensors["vib"]   = vibActive ? 1 : 0;
    sensors["light"] = light;
    sensors["cap"]   = cap;

    serializeJson(doc, Serial);
    Serial.println();
  }
}
